backend:
  name: git-gateway
  branch: gh-pages

media_folder: "assets/img/uploads"

collections:
    - label: "Post"
      name: "post"
      folder: "_posts"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
        - label: "Layout"
          name: "layout"
          widget: "hidden"
          default: "post"
        - label: "Title"
          name: "title"
          widget: "string"
        - label: "Category"
          name: "categories"
          widget: "select"
          options: ["currentissue", "todaysresearch", "jadimikir"]
        - label: "Publish Date"
          name: "date"
          widget: "datetime"
          default: ""
          dateFormat: "DD.MM.YYYY" # e.g. 24.12.2021
          timeFormat: "HH:mm" # e.g. 21:07
          format: "LLL"
        - label: "Permalink"
          name: "permalink"
          widget: "hidden"
          default: "/:categories/:title"
        - label: "Thumbnail Image"
          name: "thumb"
          widget: "image"
        - label: "Credit"
          name: "credit"
          widget: "object"
          fields:
              - label: "Penulis"
                name: "author"
                widget: "string"
              - label: "Illustrator/Komikus"
                name: "comic"
                widget: "string"
              - label: "Periset"
                name: "research"
                widget: "string"
              - label: "Penata Letak"
                name: "layout"
                widget: "string"
              - label: "Desainer Grafis"
                name: "graphic"
                widget: "string"
        - label: "Infographic"
          name: "images"
          widget: "list"
          fields:
              - label: "Image"
                name: "image"
                widget: "image"
        - label: "Content"
          name: "body"
          widget: "markdown"
